/**
 * @file    http_asset.c
 * @brief   The built-in single-page UI served at GET / when no --webroot is set.
 *
 * A pure data blob: one over-length string literal holding the HTML + CSS + JS
 * of the live RX view. Split out of http.c so the server logic isn't buried
 * under ~380 lines of markup. Referenced by the router in http_routes.c via
 * @c zt_http_index / @c zt_http_index_len (see http_internal.h).
 *
 * @author  Iskandar Putra (www.iskandarputra.com)
 * @copyright Copyright (c) 2026 Iskandar Putra. All rights reserved.
 * @license MIT — see LICENSE for details.
 */
#include "http_internal.h"

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Woverlength-strings"
const char zt_http_index[] =
    /* ---- HTML head ---- */
    "<!DOCTYPE html><html lang='en'><head><meta charset='utf-8'>"
    "<meta name='viewport' content='width=device-width,initial-scale=1'>"
    "<title>zyterm</title><style>\n"
    ":root{--bg:#0a0a0f;--sf:#12121a;--sf2:#1a1a24;--bd:#252535;"
    "--tx:#c8cad8;--dm:#585b70;--ac:#7aa2f7;--gn:#9ece6a;--rd:#f7768e;"
    "--yl:#e0af68;--tl:#73daca;--r:6px}\n"
    "*{box-sizing:border-box;margin:0;padding:0}\n"
    "body{font-family:'Cascadia Code','JetBrains Mono','Fira Code','SF Mono',monospace;"
    "background:var(--bg);color:var(--tx);height:100vh;display:flex;"
    "flex-direction:column;overflow:hidden;font-size:13px}\n"
    /* header */
    ".hdr{display:flex;align-items:center;padding:10px 16px;background:var(--sf);"
    "border-bottom:1px solid var(--bd);gap:12px;flex-shrink:0}\n"
    ".hdr .logo{font-size:15px;font-weight:700;color:var(--ac);letter-spacing:-.5px}\n"
    ".hdr .logo span{color:var(--dm);font-weight:400}\n"
    ".dot{width:8px;height:8px;border-radius:50%;background:var(--gn);"
    "box-shadow:0 0 6px var(--gn);transition:all .3s}\n"
    ".dot.off{background:var(--rd);box-shadow:0 0 6px var(--rd)}\n"
    ".st{color:var(--dm);font-size:12px}\n"
    ".dev{color:var(--tl);font-size:12px;font-weight:500}\n"
    ".stats{margin-left:auto;display:flex;gap:16px;color:var(--dm);font-size:12px}\n"
    ".stats b{color:var(--tx);font-weight:500}\n"
    /* toolbar */
    ".bar{display:flex;align-items:center;padding:6px 16px;background:var(--sf);"
    "border-bottom:1px solid var(--bd);gap:6px;flex-shrink:0;flex-wrap:wrap}\n"
    ".btn{background:var(--sf2);color:var(--dm);border:1px solid var(--bd);"
    "border-radius:var(--r);padding:4px 10px;cursor:pointer;font-size:11px;"
    "font-family:inherit;transition:all .15s;display:inline-flex;"
    "align-items:center;gap:4px}\n"
    ".btn:hover{background:var(--bd);color:var(--tx)}\n"
    ".btn.on{background:var(--ac);color:#0a0a0f;border-color:var(--ac)}\n"
    ".btn.on:hover{opacity:.85}\n"
    ".sep{width:1px;height:20px;background:var(--bd);margin:0 4px}\n"
    ".bar label{color:var(--dm);font-size:11px}\n"
    ".bar select{background:var(--sf2);color:var(--tx);border:1px solid var(--bd);"
    "border-radius:var(--r);padding:3px 6px;font-size:11px;font-family:inherit}\n"
    /* log area */
    ".log-wrap{flex:1;overflow:hidden;position:relative}\n"
    "#log{position:absolute;inset:0;overflow-y:auto;overflow-x:hidden;"
    "padding:8px 16px;font-size:12.5px;line-height:1.6;"
    "white-space:pre-wrap;word-break:break-all;"
    "user-select:text;-webkit-user-select:text;"
    "scrollbar-width:thin;scrollbar-color:#333 transparent}\n"
    "#log::-webkit-scrollbar{width:6px}\n"
    "#log::-webkit-scrollbar-track{background:transparent}\n"
    "#log::-webkit-scrollbar-thumb{background:#333;border-radius:3px}\n"
    "#log::-webkit-scrollbar-thumb:hover{background:#555}\n"
    ".ln{display:block;min-height:1.6em}\n"
    ".ts{color:#585b70}\n"
    /* TX echo lines */
    ".ln.txl{opacity:.85}\n"
    ".txp{color:var(--gn);font-weight:600}\n"
    ".txd{color:var(--tl)}\n"
    /* input bar */
    ".inp{display:flex;align-items:center;padding:8px 16px;background:var(--sf);"
    "border-top:1px solid var(--bd);gap:8px;flex-shrink:0}\n"
    ".inp .pr{color:var(--ac);font-weight:600}\n"
    ".inp input{flex:1;background:var(--sf2);color:var(--tx);"
    "border:1px solid var(--bd);border-radius:var(--r);"
    "padding:6px 10px;font-size:13px;font-family:inherit;outline:none}\n"
    ".inp input:focus{border-color:var(--ac)}\n"
    ".inp .go{background:var(--ac);color:#0a0a0f;border:none;"
    "border-radius:var(--r);padding:6px 14px;font-size:12px;"
    "font-weight:600;cursor:pointer;font-family:inherit}\n"
    ".inp .go:hover{opacity:.85}\n"
    /* terminal input mirror */
    ".tinp{display:flex;align-items:center;padding:4px 16px 0;background:var(--sf);"
    "gap:8px;flex-shrink:0;font-size:11px;color:var(--dm)}\n"
    ".tinp .lb{color:var(--yl);font-weight:600;font-size:10px}\n"
    ".tinp .tv{color:var(--tx);opacity:.7}\n"
    /* toast notification */
    ".toast{position:fixed;bottom:80px;left:50%;transform:translateX(-50%);"
    "background:var(--sf2);color:var(--tx);border:1px solid var(--bd);"
    "border-radius:var(--r);padding:6px 16px;font-size:12px;"
    "opacity:0;transition:opacity .3s;pointer-events:none;z-index:10}\n"
    ".toast.vis{opacity:1}\n"
    "</style></head>\n"
    /* ---- HTML body ---- */
    "<body>\n"
    "<div class='hdr'>"
    "<div class='logo'>zyterm <span>live</span></div>"
    "<div class='dot' id='dot'></div>"
    "<div class='st' id='st'>connecting&#8230;</div>"
    "<div class='dev' id='dev'></div>"
    "<div class='stats'>"
    "<span>RX <b id='rx'>0 B</b></span>"
    "<span>TX <b id='txc'>0 B</b></span>"
    "<span>Lines <b id='lc'>0</b></span>"
    "</div></div>\n"
    "<div class='bar'>"
    "<button class='btn on' id='ab' onclick='tScr()'>&#8595; Autoscroll</button>"
    "<button class='btn' id='pb' onclick='tPause()'>&#9646;&#9646; Pause</button>"
    "<button class='btn' id='tb' onclick='tTs()'>&#9201; Timestamps</button>"
    "<div class='sep'></div>"
    "<label>Max lines</label>"
    "<select id='ml' onchange='ML=+this.value'>"
    "<option value='1000'>1,000</option>"
    "<option value='5000'>5,000</option>"
    "<option value='10000' selected>10,000</option>"
    "<option value='50000'>50,000</option>"
    "<option value='0'>Unlimited</option></select>"
    "<div class='sep'></div>"
    "<button class='btn' onclick='sav()'>Save .txt</button>"
    "<button class='btn' onclick='cop()'>Copy</button>"
    "<button class='btn' onclick='clr()'>&#10005; Clear</button>"
    "</div>\n"
    "<div class='log-wrap'><div id='log'></div></div>\n"
    "<div class='tinp' id='tinp' style='display:none'>"
    "<span class='lb'>TERMINAL</span>"
    "<span class='tv' id='tbuf'></span>"
    "</div>\n"
    "<div class='inp'>"
    "<span class='pr'>&#10095;</span>"
    "<input id='tx' type='text' placeholder='Type command and press Enter to send...' "
    "autocomplete='off' spellcheck='false'>"
    "<button class='go' onclick='snd()'>Send</button>"
    "</div>\n"
    "<div class='toast' id='toast'></div>\n"
    /* ---- JavaScript ---- */
    "<script>\n"
    "'use strict';\n"
    /* state */
    "var "
    "AS=true,PA=false,TS=false,ML=10000,RXB=0,TXB=0,LC=0,pq=[],raf=0,res='',lbuf='',lbT=0,"
    "txbuf='',txT=0;\n"
    "var hist=[],hIdx=-1;\n"
    "var L=document.getElementById('log'),"
    "dot=document.getElementById('dot'),"
    "stE=document.getElementById('st'),"
    "txI=document.getElementById('tx');\n"
    /* 256-color table */
    "var C16=['#000','#c00','#0a0','#c50','#00c','#c0c','#0cc','#ccc',"
    "'#555','#f55','#5f5','#ff5','#55f','#f5f','#5ff','#fff'];\n"
    "function c256(n){"
    "if(n<16)return C16[n];"
    "if(n<232){n-=16;var r=Math.floor(n/36)*51,g=Math.floor(n%36/6)*51,b=(n%6)*51;"
    "return'rgb('+r+','+g+','+b+')'}"
    "var v=8+(n-232)*10;return'rgb('+v+','+v+','+v+')'}\n"
    /* ANSI SGR state */
    "var fg='',bg='',bo=false,dm=false,it=false,ul=false;\n"
    "function aR(){fg='';bg='';bo=false;dm=false;it=false;ul=false}\n"
    "function aS(){"
    "var s='';"
    "if(fg)s+='color:'+fg+';';"
    "if(bg)s+='background:'+bg+';';"
    "if(bo)s+='font-weight:700;';"
    "if(dm)s+='opacity:.6;';"
    "if(it)s+='font-style:italic;';"
    "if(ul)s+='text-decoration:underline;';"
    "return s}\n"
    "function aA(p){"
    "for(var i=0;i<p.length;i++){var v=p[i];"
    "if(v===0)aR();"
    "else if(v===1){bo=true;dm=false}"
    "else if(v===2){dm=true;bo=false}"
    "else if(v===3)it=true;"
    "else if(v===4)ul=true;"
    "else if(v===22){bo=false;dm=false}"
    "else if(v===23)it=false;"
    "else if(v===24)ul=false;"
    "else if(v>=30&&v<=37)fg=C16[v-30+(bo?8:0)];"
    "else if(v===39)fg='';"
    "else if(v>=40&&v<=47)bg=C16[v-40];"
    "else if(v===49)bg='';"
    "else if(v>=90&&v<=97)fg=C16[v-82];"
    "else if(v>=100&&v<=107)bg=C16[v-92];"
    "else if(v===38&&i+1<p.length){"
    "if(p[i+1]===5&&i+2<p.length){fg=c256(p[i+2]);i+=2}"
    "else if(p[i+1]===2&&i+4<p.length){"
    "fg='rgb('+p[i+2]+','+p[i+3]+','+p[i+4]+')';i+=4}}"
    "else if(v===48&&i+1<p.length){"
    "if(p[i+1]===5&&i+2<p.length){bg=c256(p[i+2]);i+=2}"
    "else if(p[i+1]===2&&i+4<p.length){"
    "bg='rgb('+p[i+2]+','+p[i+3]+','+p[i+4]+')';i+=4}}"
    "}}\n"
    /* parse ANSI text to HTML spans */
    "function aP(t){"
    "var h='',i=0;"
    "while(i<t.length){"
    "if(t.charCodeAt(i)===0x1b&&t[i+1]==='['){"
    "i+=2;var ps=[],nm='';"
    "while(i<t.length){var ch=t[i];"
    "if(ch>='0'&&ch<='9'){nm+=ch;i++}"
    "else if(ch===';'){ps.push(nm?+nm:0);nm='';i++}"
    "else if(ch==='m'){ps.push(nm?+nm:0);i++;break}"
    "else{i++;break}}"
    "aA(ps)}"
    /* skip other ESC sequences (cursor moves, erase, etc.) */
    "else if(t.charCodeAt(i)===0x1b){"
    "i++;"
    "if(i<t.length&&t[i]==='['){i++;while(i<t.length&&t.charCodeAt(i)>=0x20&&t.charCodeAt(i)<="
    "0x3f)i++;if(i<t.length)i++}"
    "else if(i<t.length)i++}"
    "else{"
    "var r='';"
    "while(i<t.length&&t.charCodeAt(i)!==0x1b){"
    "var c=t[i];"
    "if(c==='<')r+='&lt;';"
    "else if(c==='>')r+='&gt;';"
    "else if(c==='&')r+='&amp;';"
    "else if(c!=='\\r')r+=c;i++}"
    "if(r){var s=aS();"
    "if(s)h+='<span style=\"'+s+'\">'+r+'</span>';"
    "else h+=r}}}"
    "return h}\n"
    /* HTML-escape plain text */
    "function he(t){"
    "return t.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}\n"
    /* formatting helpers */
    "function fB(n){"
    "if(n<1024)return n+' B';"
    "if(n<1048576)return(n/1024).toFixed(1)+' KB';"
    "return(n/1048576).toFixed(2)+' MB'}\n"
    "function tN(){"
    "var d=new Date();"
    "return('0'+d.getHours()).slice(-2)+':'+('0'+d.getMinutes()).slice(-2)+':'"
    "+('0'+d.getSeconds()).slice(-2)+'.'+('00'+d.getMilliseconds()).slice(-3)}\n"
    /* toast notification */
    "var toT=0;\n"
    "function toast(msg){"
    "var el=document.getElementById('toast');"
    "el.textContent=msg;el.classList.add('vis');"
    "clearTimeout(toT);toT=setTimeout(function(){el.classList.remove('vis')},2000)}\n"
    /* batch render via requestAnimationFrame */
    "function flush(){"
    "raf=0;if(!pq.length)return;\n"
    "var all=lbuf+pq.join('');pq=[];\n"
    /* split on \n — last element is the incomplete tail (may be empty) */
    "var parts=all.split('\\n');\n"
    "lbuf=parts[parts.length-1];\n" /* keep partial line for next flush */
    "var html='';\n"
    "for(var j=0;j<parts.length-1;j++){"
    "var ln=parts[j];\n"
    /* strip trailing \r from CRLF, then handle bare \r overwrites */
    "if(ln.charCodeAt(ln.length-1)===13)ln=ln.slice(0,-1);\n"
    "if(ln.indexOf('\\r')>=0){var segs=ln.split('\\r');ln=segs[segs.length-1]}\n"
    "if(!ln)continue;\n"
    "html+='<div class=\"ln\">';"
    "if(TS)html+='<span class=\"ts\">['+tN()+'] </span>';\n"
    "html+=aP(ln);"
    "html+='</div>';LC++}\n"
    "if(html)L.insertAdjacentHTML('beforeend',html);\n"
    "if(ML>0&&L.childElementCount>ML){"
    "var ex=L.childElementCount-ML;"
    "var range=document.createRange();"
    "range.setStartBefore(L.firstElementChild);"
    "range.setEndAfter(L.children[ex-1]);"
    "range.deleteContents()}\n"
    "document.getElementById('rx').textContent=fB(RXB);\n"
    "document.getElementById('txc').textContent=fB(TXB);\n"
    "document.getElementById('lc').textContent=LC.toLocaleString();\n"
    "if(AS)L.scrollTop=L.scrollHeight}\n"
    /* flush lbuf as incomplete line after idle timeout */
    "function lbFlush(){"
    "lbT=0;if(!lbuf)return;\n"
    "var ln=lbuf;lbuf='';\n"
    "if(ln.charCodeAt(ln.length-1)===13)ln=ln.slice(0,-1);\n"
    "if(ln.indexOf('\\r')>=0){var segs=ln.split('\\r');ln=segs[segs.length-1]}\n"
    "var html='<div class=\"ln\">';"
    "if(TS)html+='<span class=\"ts\">['+tN()+'] </span>';\n"
    "html+=aP(ln);html+='</div>';LC++;\n"
    "L.insertAdjacentHTML('beforeend',html);\n"
    "if(AS)L.scrollTop=L.scrollHeight}\n"
    /* add RX data with residual escape handling */
    "function addD(t){"
    "if(PA)return;"
    "t=res+t;res='';\n"
    "var le=t.lastIndexOf('\\x1b');\n"
    "if(le>=0&&le>t.length-20){"
    "var tail=t.substring(le);"
    "if(tail.length<3||(tail[1]==='['&&!/[a-zA-Z]/.test(tail.slice(2)))){"
    "res=tail;t=t.substring(0,le)}}\n"
    "if(t){pq.push(t);if(!raf)raf=requestAnimationFrame(flush);\n"
    "clearTimeout(lbT);lbT=setTimeout(lbFlush,150)}}\n"
    /* add TX echo line — buffer keystrokes, render on CR/LF or debounce */
    "function txFlush(){"
    "txT=0;if(!txbuf)return;\n"
    "var t=txbuf.replace(/[\\r\\n]/g,'');\n"
    "txbuf='';\n"
    "t=t.replace(/[\\x00-\\x08\\x0b\\x0c\\x0e-\\x1f]/g,'');\n" /* strip control chars (tab etc)
                                                                */
    "if(!t)return;\n"
    "var div=document.createElement('div');"
    "div.className='ln txl';\n"
    "var h='';"
    "if(TS)h+='<span class=\"ts\">['+tN()+'] </span>';\n"
    "h+='<span class=\"txp\">&#10095; </span>';"
    "h+='<span class=\"txd\">'+he(t)+'</span>';\n"
    "div.innerHTML=h;L.appendChild(div);LC++;\n"
    "if(AS)L.scrollTop=L.scrollHeight}\n"
    "function addTx(raw){"
    "if(PA)return;\n"
    "TXB+=raw.length;\n"
    "txbuf+=raw;\n"
    "if(/[\\r\\n]/.test(raw)){clearTimeout(txT);txFlush();return}\n"
    "clearTimeout(txT);txT=setTimeout(txFlush,150)}\n"
    /* SSE connection with auto-reconnect */
    "var es=null;\n"
    "function conn(){"
    "es=new EventSource('/stream');\n"
    "es.onopen=function(){"
    "dot.classList.remove('off');stE.textContent='connected';"
    "loadInfo()};\n"
    "es.onerror=function(){"
    "dot.classList.add('off');stE.textContent='reconnecting\\u2026';"
    "es.close();setTimeout(conn,2000)};\n"
    /* RX data (default unnamed event) */
    "es.onmessage=function(e){"
    "var r=atob(e.data);RXB+=r.length;addD(r)};\n"
    /* TX echo event */
    "es.addEventListener('tx',function(e){"
    "var r=atob(e.data);addTx(r)});\n"
    /* Terminal input sync event */
    "es.addEventListener('input',function(e){"
    "var tb=document.getElementById('tbuf'),"
    "tw=document.getElementById('tinp');\n"
    "if(!e.data){tw.style.display='none';return}\n"
    "var r=atob(e.data);"
    "tw.style.display='flex';tb.textContent=r})}\n"
    "conn();\n"
    /* Fetch device info for the header */
    "function loadInfo(){"
    "fetch('/api/state').then(function(r){return r.json()}).then(function(s){"
    "document.getElementById('dev').textContent=s.device+' @ '+s.baud+' baud';"
    "document.title='zyterm \\u2014 '+s.device"
    "}).catch(function(){})}\n"
    /* UI controls */
    "function tScr(){"
    "AS=!AS;document.getElementById('ab').classList.toggle('on',AS);"
    "if(AS)L.scrollTop=L.scrollHeight}\n"
    "function tPause(){"
    "PA=!PA;var b=document.getElementById('pb');"
    "b.classList.toggle('on',PA);"
    "b.innerHTML=PA?'&#9654; Resume':'&#9646;&#9646; Pause'}\n"
    "function tTs(){"
    "TS=!TS;document.getElementById('tb').classList.toggle('on',TS)}\n"
    "function clr(){"
    "L.innerHTML='';LC=0;RXB=0;TXB=0;lbuf='';clearTimeout(lbT);txbuf='';clearTimeout(txT);aR();"
    "document.getElementById('rx').textContent='0 B';"
    "document.getElementById('txc').textContent='0 B';"
    "document.getElementById('lc').textContent='0'}\n"
    "function cop(){"
    "navigator.clipboard.writeText(L.innerText).then(function(){"
    "toast('Copied to clipboard')})}\n"
    "function sav(){"
    "var b=new Blob([L.innerText],{type:'text/plain'});"
    "var a=document.createElement('a');"
    "a.href=URL.createObjectURL(b);"
    "a.download='zyterm_'+new Date().toISOString().replace(/[:.]/g,'-')+'.txt';"
    "a.click();URL.revokeObjectURL(a.href);"
    "toast('Saved')}\n"
    /* Send with command history */
    "function snd(){"
    "var v=txI.value;"
    "if(!v)return;"
    "hist.push(v);hIdx=-1;"
    "fetch('/tx',{method:'POST',body:v+'\\r\\n'}).catch(function(){});"
    "txI.value='';txI.focus()}\n"
    /* Keyboard: Enter to send, Up/Down for history */
    "txI.addEventListener('keydown',function(e){"
    "if(e.key==='Enter'){e.preventDefault();snd()}"
    "else if(e.key==='ArrowUp'){"
    "e.preventDefault();"
    "if(hist.length===0)return;"
    "if(hIdx<0)hIdx=hist.length;"
    "if(hIdx>0){hIdx--;txI.value=hist[hIdx]}}"
    "else if(e.key==='ArrowDown'){"
    "e.preventDefault();"
    "if(hIdx<0)return;"
    "hIdx++;"
    "if(hIdx>=hist.length){hIdx=-1;txI.value=''}"
    "else txI.value=hist[hIdx]}});\n"
    /* auto-detect manual scroll */
    "L.addEventListener('scroll',function(){"
    "if(L.scrollHeight-L.scrollTop-L.clientHeight>50){"
    "if(AS){AS=false;document.getElementById('ab').classList.remove('on')}}});\n"
    "</script></body></html>";
#pragma GCC diagnostic pop

const size_t zt_http_index_len = sizeof zt_http_index - 1;
